### ISSUE TITLE
Using case changes ordering

### ISSUE THREAD

**Issue by nikoloza** [vigour-io/brisky#3]
In this code you'll see Search is in the top of everything, but it's inside case. That changes ordering and after rendering appears at the end of the list:  https://github.com/vigour-io/play-sidebar/blob/e9a88536595b9b5be84354c24a1facdbf1215729/lib/menu/index.js#L42-L61

![image](https://cloud.githubusercontent.com/assets/962224/15896876/77561660-2d92-11e6-9168-27583648d0ff.png)

**Comment by jimdebeer** [comment]
@nikoloza pretty sure this is done

**Comment by nikoloza** [comment]
yep
