### ISSUE TITLE
Jsx (and state of Brisky)

### ISSUE THREAD

**Issue by xelius** [vigour-io/brisky#9]
Hi, a bit late to the game I recently ran across  Jims very interesting zeit-day talk. I really like the ideas behind the whole stack he laid out there.

However, seems the docs are a bit barebones (no surprise really given this isn’t React or anything). 

In the talk I think jsx-elements are mentinoned, but I can’t find any example of brisky using this, at least not after a quick browse of the repos. Is this not implented yet or am I just missing something?

And generally, are brisky in active development? If I want to try to using it for a project, is this something you would recommend at this stage?

Thanks!

**Comment by jimdebeer** [comment]
hey @xeluis its all a bit in a alpha state but you can find some examples in the jsx test folder of a repo called 'builder-boy'

**Comment by xelius** [comment]
Thats great, thanks @jimdebeer. I'll have a look.

(Because I'm curious,  are you working privately and gradually committing to the Github repo or are all the dev in the open here?)
